# Rigbe G. Weldatsadik
# 10.12.2017
# rigbe.weldatsadik@helsinki.fi
# Two protugese schools' Students Performance of Math and Portugese language DataSet (https://archive.ics.uci.edu/ml/datasets/Student+Performance)

library(dplyr)

# reading the datasets
math <- read.table("data/student-mat.csv", sep = ";" , header=TRUE)
por <- read.table("data/student-por.csv", sep = ";" , header=TRUE)

# exploring
# the math dataset has 395 observation and 33 variables(of factor and int types), while the por dataset has the same 33 variables but 649 observations
str(math)
str(por)
dim(math)
dim(por)

# I will merge the maths and protugese datasets based on the common students that took both classes and based on every variable other than the 3 grades and
# the variables'studytime','schoolsupyes','famsupyes','paidclass' which might be specific to the two subjects. For instance, I would imagine there would be
# few instances of extra paid classes for the portugese language than mathematics.

math_por <- merge(math,por,by=c("school","sex","age","address","famsize","Pstatus",
                             "Medu","Fedu","Mjob","Fjob","reason","nursery","internet",
                             "guardian","guardian","traveltime","failures",
                             "activities","higher","romantic",
                             "famrel","freetime","goout","Dalc","Walc","health","absences"),suffixes = c(".math",".por"))


# So we have 85 students whose info matches in both datasets and the 3 grades and the paid variables will be suffixed with math and por to indicate
# which data set the values are from
dim(math_por)
str(math_por)
glimpse(math_por)


# saving the merged data
write.table(math_por,file = "data/math_por.csv", sep = "\t")

# we will also do some data wrangling for the LDA part, particularly scaling and creating a binary variable from the continuous grade3 values
math_por2 <- math_por[sapply(math_por,class)!= "factor"]
cor_matrix<-cor(math_por2) 
library(corrplot)
library(GGally)
library(ggplot2)

corrplot(cor_matrix, method="circle",type="upper",tl.pos = "d",tl.cex = 0.8)
ggpairs(math_por2, mapping = aes(), lower = list(combo = wrap("facethist", bins = 20)))

summary(math_por2)

mathPor2_scaled <- as.data.frame(scale(math_por2))
str(mathPor2_scaled)
G3_binary.por = ifelse(mathPor2_scaled$G3.por >= 0.65,'pass','fail')
G3_binary.math = ifelse(mathPor2_scaled$G3.math >= 0.65,'pass','fail')

mathPor2_scaled <- mathPor2_scaled %>% dplyr::select(-one_of('G3.por','G3.math'))


mathPor2_scaled <- data.frame(mathPor2_scaled, G3_binary.por,G3_binary.math)

write.table(mathPor2_scaled,file = "data/mathPor2_scaled.csv", sep = "\t")

