---
title: IODS course final project
author: "Rigbe G. Weldatsadik"
date: 10/12/2016
output:
  html_document:
    theme: cosmo
    toc: true
    toc_depth: 2
    fig_caption: true
    fig_width: 6
    fig_height: 4
    code_folding: hide
---

## Abstract

## Research question and hypothesis

## A link to your data wrangling script

## Description of data and its variables

## Explorations of the variables of interest

## Method description
# First I will do a linear regression of the final math and portugese grades (separately) with all the variables except those that might be specific to the two subjects(such as weekly study time,extra educational school support,family educational support,extra paid classes) which is done in the data wrangling part and also except the previous two grades.
# I am fitting models separately for the two subjects to see if the explanatory variables of significance differs and i could have done this before merging the two datasets but i wanted to do it on only those students whose info matches on almost all variables between both subjects

```{r}
library(dplyr)

math_por <- read.table("data/math_por.csv",header=T, sep="\t")
#math
math2 <- math_por %>% dplyr::select(-one_of('G1.math','G2.math','paid.por','G1.por','G2.por','G3.por','studytime.por','schoolsup.por','famsup.por'))
str(math2)
mathGrade_lm<-lm(G3.math~., data=math2)
summary(mathGrade_lm)
#portugese
por2 <- math_por %>% dplyr::select(-one_of('G1.por','G2.por','paid.math','G1.math','G2.math','G3.math','studytime.math','schoolsup.math','famsup.math'))
porGrade_lm<-lm(G3.por~., data=por2)
summary(porGrade_lm)
```